# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5519b4b9e9f2a0323aadc34f7e36ba96ddd873c6d99d7fb9212e0cb45020eb603ddbdc50be35adb773ddbd4975ca6d8a9343787e8ad9d698a895f63789100122

test:
  secret_key_base: fb079c788246c3397b2de78039bf40cc02298f7238eee396b3d236c0324ea81c6a22d01a3ae3fb42b794a7b555f652c9208712dd76dcb76b7cfed0e646a9818c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
